availproject/docs

- docs/Architecture/avail-system-overview.md
- docs/Running Avail/avail-light-client-da.md
- docs/Running Avail/avail-node-management.md
- docs/Running Avail/build-data-availability.md
- docs/faq.md
- docs/introduction.md
- docs/quick-start.md
Hi, Changes pushed in this VivekNew branch takes care of the URL corrections and update the 'data-avail' binary build instructions. Please review and arrange to merge if they are Ok. Regards...
> URL and Build updates1

- docs/using-avail/use-cases-and-examples/communicating-with-avail.md
Links to examples of communicating with Avail.
> Add links to Avail examples.

- docs/using-avail/use-cases-and-examples/validiums.md
Fix typo and addresses for validiums.
> Fix typo and addresses.

- docs/using-avail/use-cases-and-examples/validiums.md
> Fix validiums example link.

- docs/using-avail/use-cases-and-examples/validiums.md
Verification contract implementation in yul and uses keccak256.
> Add verification contract that uses keccak256.

- docs/validators/run-avail/validator-ops/0030-avail-upgrade-validator-node.md
- docusaurus.config.js
- yarn.lock
- Fixes broken redirects applied in https://github.com/availproject/availproject.github.io/pull/39
- Updates Docusaurus and related dependencies
> fix: redirects & update deps

- docs/develop/validium-l3/validiums.md
Update documentation to match rpc transaction index mapping.
https://github.com/availproject/avail/pull/198
> Update doc to match transaction mapping to data index.

- docs/validators/chilling.md
- docusaurus.config.js
- Updated Plausible Analytics configuration.
- Refocused chilling + slashing guide on just chilling ("Chill Your Validator") as the guide is not actually about slashing, rather, slashing is a consequence of involuntary chilling.
> update: more restructure followups

- README.md
- src/css/custom.css
- src/data/content-data.js
> update: readme + post-restructure tweaks

- docs/node/full-node/full-node-binaries.md
- docs/node/full-node/full-node-docker.md
- docs/validators/validator-node/validator-node-docker.md
this pr fixes broken links of chainspec files
> fix links of chainspec files

- docusaurus.config.js
- src/css/custom.css
- src/data/content-data.js
- src/pages/index.js
- Fixes Twitter link (accidentally added an 's' after 'Project'
- Uses Avail blogs for 'Data Availability Resource' section in the Footer
- Transforms 'Repositories' section in the Footer to 'Node Repositories
- Removes redundancy in the 'Build Modular Solution' card and calls out app-chains.
- General tweaks as need.
> update: general enh post-restructure

- docs/about/accounts.md
- docs/about/explorer.md
- docs/about/introduction.md
- Expands account context within the "Getting Started" guide for creating an account.
- Includes references to available resources (i.e. Substrate docs.)
- Includes improvements to the "Use the Explorer" document with additional updates on the way.
> update: init get started updates

- src/css/custom.css
- src/data/content-data.js
- General styling edits to network section
- Slightly bigger title
- Improve tab styling
- Refine the "Build Modular Solutions" card to emphasize key features more broadly and focus tutorial highlights on prioritized solutions
> update: general homepage edits

- docs/about/introduction/validiums.md
- docs/api/light-client/light-client-embedding.md
- docs/api/light-client/using-light-client.md
- docs/operate/requirements.md
- docs/operate/validator/0070-chilling.md
> chore: fix typos

- .github/workflows/build.yml
- Adds build scripts
- Adds link check
> feat: initial ci

- .github/workflows/build.yml
- cspell.json
- docs/operate/validator/0050-validator-monitoring.md
- Adds spell check as part of lint checks
- Tested in https://github.com/availproject/availproject.github.io/pull/129
> feat: spell check

- docs/faqs.md
- sidebars.js
- src/components/EcosystemSection.js
- src/components/Home.js
- src/css/custom.css
- src/data/content-data.js
- Clean up and simplify components.
- Make FAQs its own document until new design is adapted.
> update: homepage styling updates

- src/css/custom.css
> update: codeblock styling

- docs/networks.md
- docs/operate/node/0010-light-client.md
- docs/operate/requirements.md
- docusaurus.config.js
- src/components/Home.js
- src/components/TutorialsCard.js
- src/data/content-data.js
- Further narrows scope of cards, polishes styling, and adds download links for light client.
- Make "Networks" its own page on the navbar, offer temp temp temp solution for navigating back to key guides and the homepage.
> update: further homepage styling improvements

- docs/build/quickstart.md
- docs/networks.md
- docs/operate/node/0010-light-client.md
- docs/operate/requirements.md
- docusaurus.config.js
- Reintroduce e2e flow for lc guide
- Generate master table for network info
- General improvements
> update: node & lc content enh

- docusaurus.config.js
- src/css/custom.css
Adds announcement bar and announcement for Kate testnet deprecation with upcoming incentivized testnet.
> feat: announcement bar

- cspell.json
- docs/operate/validator/0010-validator-node-binaries.md
- docs/operate/validator/0070-chilling.md
fix some typos, and update cspell.json
> Fix some typos

- docs/networks.md
- src/data/content-data.js
Replaces download links with guide links for better UX.
> update: enhance lc homepage card

- docs/api/validiums.md
Add addresses for Goldberg network.
> Add contract details for goldberg network.

- docs/operate/validator/0030-staking.md
Hey been seeing this issue in the discord recently and wanted to add documentation on how to author_rotateKeys for docker. I closed the other PR and reopened it with a different branch name. 
-Frazz
> Added steps to rotate session keys using docker

- docs/build/op-stack/op-stack.md
I have fixed some directory in  op-stack.md file
Please check.
Thanks
> correct directory in  op-stack.md file

- docs/about/accounts.md
- docs/about/faucet.md
- docs/about/introduction/light-clients.md
I love Avail, I've edited a few details I spotted while reviewing documents to make them look more organized and professional!
> fixing typos and update light-clients.md

- .all-contributorsrc
- CONTRIBUTING.md
- README.md
Not sure how it will turn out tbh. Will be on watch duty in case of failure.
> Trying out all-contributors bot on main.

- docs/operate/validator/0010-basics.md
- docs/operate/validator/0020-simple-deployment.md
- docs/operate/validator/0060-validator-upgrade.md
- Use `queryString` (see [reference](https://docusaurus.io/docs/markdown-features/tabs#query-string)) in Tabs
- Rename `availd.service` -> `avail.service` for consistency
- Minor edits
> chore: docs cleanup

- docs/clash-of-nodes/madara-karnot.md
> chore: fix quote indentation

- pages/docs/operate-a-node/run-a-light-client/Reference/configure-a-light-client.mdx
Updating this page as per Ljubisa's suggestions
> Updating `How to Configure a Light Client` page

- pages/docs/learn-about-avail/faqs.mdx
Changing Email given to potential inbounds in the FAQs as instructed by Scott.
> Changing suggested Email Address for inbounds

- app/api-reference/avail-node-api/balances-transfer-all/page.mdx
- app/api-reference/avail-node-api/balances-transfer-allow-death/page.mdx
- app/api-reference/avail-node-api/balances-transfer-keep-alive/page.mdx
- app/api-reference/avail-node-api/da-app-keys/page.mdx
- app/api-reference/avail-node-api/da-create-application-key/page.mdx
- app/api-reference/avail-node-api/da-next-app-id/page.mdx
- app/api-reference/avail-node-api/da-submit-data/page.mdx
- app/api-reference/avail-node-api/nomination-pools-create-with-pool-id/page.mdx
- app/api-reference/avail-node-api/nomination-pools-create/page.mdx
- app/api-reference/avail-node-api/nomination-pools-join/page.mdx
- app/api-reference/avail-node-api/nomination-pools-nominate/page.mdx
- app/api-reference/avail-node-api/page.mdx
- app/api-reference/avail-node-api/staking-active-era/page.mdx
- app/api-reference/avail-node-api/staking-bond/page.mdx
- app/api-reference/avail-node-api/staking-chill/page.mdx
- app/api-reference/avail-node-api/staking-nominate/page.mdx
- app/api-reference/avail-node-api/staking-unbond/page.mdx
- app/api-reference/avail-node-api/staking-validate/page.mdx
- app/api-reference/avail-node-api/system-account/page.mdx
- app/docs/build-with-avail/interact-with-avail-da/query-balances/page.mdx
- app/docs/build-with-avail/interact-with-avail-da/read-write-on-avail/page.mdx
- app/docs/build-with-avail/interact-with-avail-da/transfer-balances/page.mdx
- package.json
Changelogs:
1. Updated all `avail-js` snippets under `API reference` to use the release `@0.4.0`.
2. Updated all `avail-js` snippets under `docs` to use the release `@0.4.0`.
3. Added new read data snippets for all three SDKs under the [read-write](https://docs.availproject.org/docs/build-with-avail/interact-with-avail-da/read-write-on-avail) page.
> Avail js updated to 0.4.0

- app/api-reference/avail-node-api/system-account/page.mdx
- app/api-reference/layout.tsx
- app/docs/layout.tsx
- app/layout.tsx
- app/user-guides/layout.tsx
- components/lib/metadata.ts
Changelogs:
1. Adding Subscan example for fetching account information via a curl command
2. Fixing preview images to display uniformly across the entire website.
> Adding-subscan-api-example

- app/docs/build-with-avail/deploy-rollup-on-avail/Optimium/arbitrum-nitro/nitro-stack/page.mdx
- app/docs/operate-a-node/run-a-full-node/full-node/page.mdx
Changelogs:
1. Corrected a misleading link
2. Added recommended config flags for RPC providers
> Adding recommended config flags for RPC providers

- app/api-reference/avail-node-api/page.mdx
This PR is being made to fix a minor formatting error that is preventing the bot from doing it's job
> chore: tweaking minor markdown
